{
 "title": "Network",
 "tags": [ "aptos-core" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   { "name": "network_id", "query": { "query": "label_values(network_id)" } },
   { "name": "role_type", "query": { "query": "label_values(role_type)" } },
   { "name": "rpc_protocol", "label": "RPC Protocol", "query": { "query": "label_values(protocol_id)" } },
   { "name": "AggInterval", "label": "Aggregation Interval", "query": "1m,5m,15m,30m,1h,3h,1d,7d" }
  ]
 },
 "panels": [
  {
   "title": "Connected Peers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Connected Peers",
   "type": "graph",
   "description": "Total Connected Peers for both inbound and outbound per peer.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role_type, network_id) (aptos_connections{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})\n",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Inbound Connected Peers",
   "type": "graph",
   "description": "Total Inbound connected peers.  There should be at most one peer with 0 inbound connections.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role_type, network_id) (aptos_connections{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", direction=\"inbound\"})",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Outbound Connected Peers",
   "type": "graph",
   "description": "Total outbound connections per peer.  Every node should have an outbound connection.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role_type, network_id)(aptos_connections{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", direction=\"outbound\"})",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Network Key Mismatches",
   "type": "graph",
   "description": "Value is > 0 if there is a mismatch between onchain and actual network key on the interface",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role_type, network_id) (aptos_network_key_mismatch{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Traffic and Rate Limiting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "VFN Public Network Inbound Allowed bytes (bytes/s)",
   "type": "graph",
   "description": "Inbound number of bytes passed through the throttler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_network_rate_limit_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", metric=\"allowed\", direction=\"inbound\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "VFN Public Network Outbound Allowed bytes (bytes/s)",
   "type": "graph",
   "description": "Outbound number of bytes passed through the throttler",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_network_rate_limit_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", metric=\"allowed\", direction=\"outbound\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "VFN Public Network Inbound Throttled bytes (bytes/s)",
   "type": "graph",
   "description": "Inbound number of bytes rate limited through the throttler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_network_rate_limit_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", metric=\"throttled\", direction=\"inbound\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "VFN Public Network Outbound Throttled bytes (bytes/s)",
   "type": "graph",
   "description": "Outbound number of bytes rate limited through the throttler",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_network_rate_limit_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", metric=\"throttled\", direction=\"outbound\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Network Inbound bytes (bytes/s)",
   "type": "graph",
   "description": "Inbound number of bytes received on the network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(aptos_network_app_inbound_traffic_sum{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",role_type=~\"$role_type\", network_id=~\"$network_id\", kubernetes_pod_name=~\"$kubernetes_pod_name\",chain_name=~\"$chain_name\", cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "quantile(0.5, rate(aptos_network_app_inbound_traffic_sum{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",role_type=~\"$role_type\", network_id=~\"$network_id\", kubernetes_pod_name=~\"$kubernetes_pod_name\",chain_name=~\"$chain_name\", cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.9, rate(aptos_network_app_inbound_traffic_sum{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",role_type=~\"$role_type\", network_id=~\"$network_id\", kubernetes_pod_name=~\"$kubernetes_pod_name\",chain_name=~\"$chain_name\", cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "p90"
    },
    {
     "expr": "quantile(0.99, rate(aptos_network_app_inbound_traffic_sum{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",role_type=~\"$role_type\", network_id=~\"$network_id\", kubernetes_pod_name=~\"$kubernetes_pod_name\",chain_name=~\"$chain_name\", cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile(0.1, rate(aptos_network_app_inbound_traffic_sum{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",role_type=~\"$role_type\", network_id=~\"$network_id\", kubernetes_pod_name=~\"$kubernetes_pod_name\",chain_name=~\"$chain_name\", cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "p10"
    }
   ]
  },
  {
   "title": "Network Outbound bytes (bytes/s)",
   "type": "timeseries",
   "description": "Outbound number of bytes sent on the network",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(aptos_network_app_outbound_traffic_sum{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",role_type=~\"$role_type\", network_id=~\"$network_id\", kubernetes_pod_name=~\"$kubernetes_pod_name\",chain_name=~\"$chain_name\", cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "quantile(0.5, rate(aptos_network_app_outbound_traffic_sum{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",role_type=~\"$role_type\", network_id=~\"$network_id\", kubernetes_pod_name=~\"$kubernetes_pod_name\",chain_name=~\"$chain_name\", cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.9, rate(aptos_network_app_outbound_traffic_sum{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",role_type=~\"$role_type\", network_id=~\"$network_id\", kubernetes_pod_name=~\"$kubernetes_pod_name\",chain_name=~\"$chain_name\", cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "p90"
    },
    {
     "expr": "quantile(.99, rate(aptos_network_app_outbound_traffic_sum{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",role_type=~\"$role_type\", network_id=~\"$network_id\", kubernetes_pod_name=~\"$kubernetes_pod_name\",chain_name=~\"$chain_name\", cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile(.1, rate(aptos_network_app_outbound_traffic_sum{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",role_type=~\"$role_type\", network_id=~\"$network_id\", kubernetes_pod_name=~\"$kubernetes_pod_name\",chain_name=~\"$chain_name\", cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "p10"
    }
   ]
  },
  {
   "title": "Network Inbound messages (messages/s)",
   "type": "graph",
   "description": "Inbound number of messages received on the network",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none", "label": "messages/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_network_app_inbound_traffic_count{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",role_type=~\"$role_type\", network_id=~\"$network_id\", kubernetes_pod_name=~\"$kubernetes_pod_name\",chain_name=~\"$chain_name\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "{{role}}-{{kubernetes_pod_name}}-{{network_id}}-{{protocol_id}}"
    }
   ]
  },
  {
   "title": "Network Outbound messages (messages/s)",
   "type": "graph",
   "description": "Outbound number of messages sent on the network",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "none", "label": "messages/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_network_app_outbound_traffic_count{metrics_source=~\"$metrics_source\", namespace=~\"$namespace\",role_type=~\"$role_type\", network_id=~\"$network_id\", kubernetes_pod_name=~\"$kubernetes_pod_name\",chain_name=~\"$chain_name\", cluster=~\"$cluster\"}[1m])",
     "legendFormat": "{{role}}-{{kubernetes_pod_name}}-{{network_id}}-{{protocol_id}}"
    }
   ]
  },
  {
   "title": "Network Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Notifications Queued",
   "type": "graph",
   "description": "TBD",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role)(aptos_network_pending_network_notifications{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role_type\",state=\"enqueued\"}) - sum by (kubernetes_pod_name, role)(aptos_network_pending_network_notifications{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role_type\",state=\"dequeued\"})",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Peer Manager Requests Queued",
   "type": "graph",
   "description": "TBD",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role)(aptos_network_pending_peer_manager_requests{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role_type\",state=\"enqueued\"}) - sum by (kubernetes_pod_name, role)(aptos_network_pending_peer_manager_requests{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role_type\",state=\"dequeued\"})",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Network Requests Queued",
   "type": "graph",
   "description": "TBD",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role)(aptos_network_pending_requests{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role_type\",state=\"enqueued\"}) - sum by (kubernetes_pod_name, role)(aptos_network_pending_requests{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role_type\",state=\"dequeued\"})",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Pending Health Check Events Queued",
   "type": "graph",
   "description": "TBD",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role)(aptos_network_pending_health_check_events{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role_type\",state=\"enqueued\"}) - sum by (kubernetes_pod_name, role)(aptos_network_pending_health_check_events{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role_type\",state=\"dequeued\"})",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Pending Wire Messages",
   "type": "graph",
   "description": "TBD",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_network_pending_wire_messages{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role_type\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Pending Connectivity Manager Requests",
   "type": "graph",
   "description": "TBD",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_network_pending_connectivity_manager_requests{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role_type\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Queuing Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPC Messages Drop Rate",
   "type": "graph",
   "description": "RPCs declined or canceled due to hitting max RPC capacity or max queue capacity.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_network_rpc_messages{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=~\"(declined|canceled)\"}[$AggInterval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}"
    }
   ]
  },
  {
   "title": "New Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inbound Pending Connection Upgrades",
   "type": "graph",
   "description": "The rate of new inbound connections on the network interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role_type, network_id) (rate(aptos_network_pending_connection_upgrades{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", direction=\"inbound\" }[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Outbound Pending Connection Upgrades",
   "type": "timeseries",
   "description": "The rate of new outbound connections on the network interface",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role_type, network_id) (rate(aptos_network_pending_connection_upgrades{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", direction=\"outbound\" }[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Inbound Connection Upgrade Latency [P50]",
   "type": "graph",
   "description": "Latency of Inbound connection upgrades",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (kubernetes_pod_name, role_type, network_id, le) (rate(aptos_network_connection_upgrade_time_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", direction=\"inbound\",role_type=~\"$role_type\",kubernetes_pod_name=~\"$kubernetes_pod_name\",network_id=~\"$network_id\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Outbound Connection Upgrade Latency [P50]",
   "type": "graph",
   "description": "Latency of Outbound connection upgrades",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (kubernetes_pod_name, role_type, network_id, le) (rate(aptos_network_connection_upgrade_time_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", direction=\"outbound\",role_type=~\"$role_type\",kubernetes_pod_name=~\"$kubernetes_pod_name\",network_id=~\"$network_id\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Inbound Connection Upgrade Latency [P90]",
   "type": "graph",
   "description": "Latency of Inbound connection upgrades",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (kubernetes_pod_name, role_type, network_id, le) (rate(aptos_network_connection_upgrade_time_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", direction=\"inbound\",role_type=~\"$role_type\",kubernetes_pod_name=~\"$kubernetes_pod_name\",network_id=~\"$network_id\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Outbound Connection Upgrade Latency [P90]",
   "type": "graph",
   "description": "Latency of Outbound connection upgrades",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (kubernetes_pod_name, role_type, network_id, le) (rate(aptos_network_connection_upgrade_time_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", direction=\"outbound\",role_type=~\"$role_type\",kubernetes_pod_name=~\"$kubernetes_pod_name\",network_id=~\"$network_id\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Inbound Connection Upgrade Latency [P99]",
   "type": "graph",
   "description": "Latency of Inbound connection upgrades",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (kubernetes_pod_name, role_type, network_id, le) (rate(aptos_network_connection_upgrade_time_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", direction=\"inbound\",role_type=~\"$role_type\",kubernetes_pod_name=~\"$kubernetes_pod_name\",network_id=~\"$network_id\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Outbound Connection Upgrade Latency [P99]",
   "type": "graph",
   "description": "Latency of Outbound connection upgrades",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (kubernetes_pod_name, role_type, network_id, le) (rate(aptos_network_connection_upgrade_time_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", direction=\"outbound\",role_type=~\"$role_type\",kubernetes_pod_name=~\"$kubernetes_pod_name\",network_id=~\"$network_id\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPC Total Request Error Rate (% requests in error)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(network_id, role_type, kubernetes_pod_name) (rate(aptos_network_rpc_messages{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\",role_type=~\"$role_type\",kubernetes_pod_name=~\"$kubernetes_pod_name\",type=\"request\",state=\"failed\"}[$AggInterval])) / sum by(network_id, role_type, kubernetes_pod_name) (rate(aptos_network_rpc_messages{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\",role_type=~\"$role_type\",kubernetes_pod_name=~\"$kubernetes_pod_name\",type=\"request\",state=~\"(sent|failed)\"}[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "RPC Total Response Error Rate (% responses in error)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(network_id, role_type, kubernetes_pod_name) (rate(aptos_network_rpc_messages{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\",role_type=~\"$role_type\",kubernetes_pod_name=~\"$kubernetes_pod_name\",type=\"response\",state=\"failed\"}[$AggInterval])) / sum by(network_id, role_type, kubernetes_pod_name) (rate(aptos_network_rpc_messages{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\",role_type=~\"$role_type\",kubernetes_pod_name=~\"$kubernetes_pod_name\",type=\"request\",state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Throughput of Total Outbound RPCs (bytes/s)",
   "type": "graph",
   "description": "Total throughput of all Outbound RPC requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role_type, network_id) (rate(aptos_network_rpc_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"sent\"}[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Throughput of Total Inbound RPCs (bytes/s)",
   "type": "graph",
   "description": "Total throughput of all Inbound RPC requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role_type, network_id)(rate(aptos_network_rpc_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Rate of Total Outbound RPCs (msg/s)",
   "type": "graph",
   "description": "Total number of all Outbound RPC requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role_type, network_id)(rate(aptos_network_rpc_messages{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", type=\"request\",state=\"sent\"}[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Rate of Total Inbound RPCs (msg/s)",
   "type": "graph",
   "description": "Total number of all Inbound RPC requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role_type, network_id)(rate(aptos_network_rpc_messages{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", type=\"request\", state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Latency of $rpc_protocol Outbound RPCs [P50]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (kubernetes_pod_name, network_id, role_type, le)(rate(aptos_network_outbound_rpc_request_latency_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", protocol_id=~\"$rpc_protocol\",kubernetes_pod_name=~\"$kubernetes_pod_name\",network_id=~\"$network_id\",role_type=~\"$role_type\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Latency of $rpc_protocol Inbound RPCs [P50]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (kubernetes_pod_name, network_id, role_type, le)(rate(aptos_network_inbound_rpc_handler_latency_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", protocol_id=~\"$rpc_protocol\",kubernetes_pod_name=~\"$kubernetes_pod_name\",network_id=~\"$network_id\",role_type=~\"$role_type\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Latency of $rpc_protocol Outbound RPCs [P90]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (kubernetes_pod_name, network_id, role_type, le)(rate(aptos_network_outbound_rpc_request_latency_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", protocol_id=~\"$rpc_protocol\",kubernetes_pod_name=~\"$kubernetes_pod_name\",network_id=~\"$network_id\",role_type=~\"$role_type\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Latency of $rpc_protocol Inbound RPCs [P90]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (kubernetes_pod_name, network_id, role_type, le)(rate(aptos_network_inbound_rpc_handler_latency_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", protocol_id=~\"$rpc_protocol\",kubernetes_pod_name=~\"$kubernetes_pod_name\",network_id=~\"$network_id\",role_type=~\"$role_type\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Latency of $rpc_protocol Outbound RPCs [P99]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (kubernetes_pod_name, network_id, role_type, le)(rate(aptos_network_outbound_rpc_request_latency_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", protocol_id=~\"$rpc_protocol\",kubernetes_pod_name=~\"$kubernetes_pod_name\",network_id=~\"$network_id\",role_type=~\"$role_type\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Latency of $rpc_protocol Inbound RPCs [P99]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (kubernetes_pod_name, network_id, role_type, le)(rate(aptos_network_inbound_rpc_handler_latency_seconds_bucket{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", protocol_id=~\"$rpc_protocol\",kubernetes_pod_name=~\"$kubernetes_pod_name\",network_id=~\"$network_id\",role_type=~\"$role_type\"}[$AggInterval])))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Direct Send",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throughput of Total Outbound Direct Sends (bytes/s)",
   "type": "graph",
   "description": "Total throughput of all Outbound Direct Send requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "avg(sum by (kubernetes_pod_name, role_type, network_id)(rate(aptos_network_direct_send_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"sent\"}[$AggInterval])))",
     "legendFormat": "avg"
    },
    {
     "expr": "quantile(0.5, sum by (kubernetes_pod_name, role_type, network_id)(rate(aptos_network_direct_send_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"sent\"}[$AggInterval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.9, sum by (kubernetes_pod_name, role_type, network_id)(rate(aptos_network_direct_send_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"sent\"}[$AggInterval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "quantile(0.99, sum by (kubernetes_pod_name, role_type, network_id)(rate(aptos_network_direct_send_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"sent\"}[$AggInterval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile(0.1, sum by (kubernetes_pod_name, role_type, network_id)(rate(aptos_network_direct_send_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"sent\"}[$AggInterval])))",
     "legendFormat": "p10"
    }
   ]
  },
  {
   "title": "Throughput of Total Inbound Direct Sends (bytes/s)",
   "type": "graph",
   "description": "Total throughput of all Inbound Direct Send requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "avg(sum by (kubernetes_pod_name, role_type, network_id)(rate(aptos_network_direct_send_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"received\"}[$AggInterval])))",
     "legendFormat": "avg"
    },
    {
     "expr": "quantile(0.5, sum by (kubernetes_pod_name, role_type, network_id)(rate(aptos_network_direct_send_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"received\"}[$AggInterval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "quantile(0.9, sum by (kubernetes_pod_name, role_type, network_id)(rate(aptos_network_direct_send_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"received\"}[$AggInterval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "quantile(0.99, sum by (kubernetes_pod_name, role_type, network_id)(rate(aptos_network_direct_send_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"received\"}[$AggInterval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile(0.1, sum by (kubernetes_pod_name, role_type, network_id)(rate(aptos_network_direct_send_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"received\"}[$AggInterval])))",
     "legendFormat": "p10"
    }
   ]
  },
  {
   "title": "Rate of Total Outbound Direct Sends (msg/s)",
   "type": "graph",
   "description": "Total number of all Outbound Direct Send requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role_type, network_id)(rate(aptos_network_direct_send_messages{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"sent\"}[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Rate of Total Inbound Direct Sends (msg/s)",
   "type": "graph",
   "description": "Total number of all Inbound Direct Send requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role_type, network_id)(rate(aptos_network_direct_send_messages{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", kubernetes_pod_name=~\"$kubernetes_pod_name\", state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  { "title": "HAProxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 175 } },
  {
   "title": "Pool Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name) (haproxy_process_pool_used_bytes{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\".*\",kubernetes_pod_name=~\".*\", role=\"haproxy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current backend sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name) (haproxy_backend_current_sessions{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\".*\",kubernetes_pod_name=~\".*\", role=\"haproxy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name) (haproxy_process_idle_time_percent{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\".*\",kubernetes_pod_name=~\".*\", role=\"haproxy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend connections rate/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name) (rate(haproxy_frontend_connections_total{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\".*\", kubernetes_pod_name=~\".*\", role=\"haproxy\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend denied connections rate/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name, __name__) (rate({__name__=~\"haproxy_.*denied.*\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", network_id=~\".*\", kubernetes_pod_name=~\".*\", role=\"haproxy\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}